name: null
favicon: null
layout_spectrum: 0.27297
typography_spectrum: 0.17693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efecee'
    - '#555555'
    - '#ffffff'
    - '#8f8e8f'
    - '#c9c7c8'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: 45578190-a057-4d84-8bd8-b11780aa2d25
    url: null
