name: moontoad
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17963
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    filter:
      notType:
        type: WebPage
    feed:
      format: rss
      path: /rss.xml
      number: 10
  - filter:
      type:
        type: Article
    permalink:
      path: '/:title/'
  - filter:
      type:
        type: WebPage
    permalink:
      path: '/:title/'
      navigable: true
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5891e'
    - '#212123'
    - '#bbbdbc'
    - '#6e6d69'
    - '#838381'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose:
  - item: b23a6902-dc23-434c-a7bb-20937e0e5063
    name: follow
    url: null
