name: moontoad
favicon: null
layout_spectrum: 0.67297
typography_spectrum: 0.17963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5891e'
    - '#212123'
    - '#bbbdbc'
    - '#6e6d69'
    - '#838381'
  brandStrength: 0
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 1
purpose:
  - name: follow
    item: 45578190-a057-4d84-8bd8-b11780aa2d25
    url: null
